In [2]:
import pandas as pd
from numpy import *
import numpy as np
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics
from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn import neighbors

In [3]:
data =pd.read_csv('train.csv')
array = data.values

for i in range(len(array)):
    if array[i][0]=="Male":
        array[i][0]=1
    else:
        array[i][0]=0


df=pd.DataFrame(array)



In [4]:
maindf =df[[0,1,2,3,4,5,6]]
mainarray=maindf.values
print (mainarray)


temp=df[7]
train_y =temp.values
# print(train_y)
# print(mainarray)
train_y=temp.values

for i in range(len(train_y)):
	train_y[i] =str(train_y[i])





[[1 17 7 ... 7 3 2]
 [1 19 4 ... 4 6 6]
 [0 18 7 ... 4 5 5]
 ...
 [1 22 5 ... 3 6 1]
 [1 19 5 ... 5 7 5]
 [0 18 5 ... 7 6 5]]


In [5]:
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg',max_iter =1000)
mul_lr.fit(mainarray, train_y)

testdata =pd.read_csv('test.csv')
test = testdata.values

for i in range(len(test)):
	if test[i][0]=="Male":
		test[i][0]=1
	else:
		test[i][0]=0




In [6]:
df1=pd.DataFrame(test)

testdf =df1[[0,1,2,3,4,5,6]]
maintestarray=testdf.values
print(maintestarray)



[[0 20 7 ... 9 5 5]
 [1 17 5 ... 5 2 4]
 [0 25 5 ... 7 2 4]
 ...
 [1 18 7 ... 6 2 7]
 [1 23 6 ... 5 4 3]
 [0 18 5 ... 3 5 6]]


In [7]:
y_pred = mul_lr.predict(maintestarray)
for i in range(len(y_pred)) :
	y_pred[i]=str((y_pred[i]))
DF = pd.DataFrame(y_pred,columns=['Predicted Personality'])
DF.index=DF.index+1
DF.index.names = ['Person No']
DF.to_csv("output.csv")



In [8]:
outputdata =pd.read_csv('output.csv')
output = outputdata.values
print(outputdata['Predicted Personality'])
outputdata.drop(outputdata.columns[:1], axis=1, inplace=True)
#print(type(outputdata))
testdata.drop(testdata.columns[:7], axis=1, inplace=True)
#print(type(testdata))

print('Prediction accuracy of test data : ')
print('{:.2%}\n'.format(metrics.accuracy_score(testdata, outputdata)))

0       dependable
1          serious
2          serious
3          serious
4      responsible
          ...     
344    extraverted
345        serious
346        serious
347    extraverted
348    extraverted
Name: Predicted Personality, Length: 349, dtype: object
Prediction accuracy of test data : 
87.11%



In [13]:
import pickle
#Create Pickle File
pd.to_pickle(mul_lr, r'C:\Users\R.K.PATI\Desktop\Rajashree\Final Project\model1.pickle')
mul_lr = pd.read_pickle(r'C:\Users\R.K.PATI\Desktop\Rajashree\Final Project\model1.pickle')


In [14]:

gender1 = int(input("Enter your gender(Male:1,Female:0):"))
age = int(input("Enter your age(17-28) : "))
EXT1 = int(input("I am the life of the party: "))
EXT2 = int(input("I don't talk a lot:  "))
EXT3 = int(input("I feel comfortable around people:  "))
EXT4 = int(input("I am quiet around strangers:  "))

EST1 = int(input("I get stressed out easily:  "))
EST2 = int(input("I get irritated easily:  "))
EST3 = int(input("I worry about things:  "))
EST4 = int(input("I change my mood a lot:  "))

AGR1 = int(input("I have a soft heart:  "))
AGR2 = int(input("I am interested in people:  "))
AGR3 = int(input("I insult people:  "))
AGR4 = int(input("I am not really interested in others:  "))

CSN1 = int(input("I am always prepared:  "))
CSN2 = int(input("I leave my belongings around:  "))
CSN3 = int(input("I follow a schedule:  "))
CSN4 = int(input("I make a mess of things:  "))

OPN1 = int(input("I have a rich vocabulary:  "))
OPN2 = int(input("I have difficulty understanding abstract ideas:  "))
OPN3 = int(input("I do not have a good imagination:  "))
OPN4 = int(input("I use difficult words:  "))



Enter your gender(Male:1,Female:0):0
Enter your age(17-28) : 22
I am the life of the party: 4
I don't talk a lot:  4
I feel comfortable around people:  4
I am quiet around strangers:  4
I get stressed out easily:  4
I get irritated easily:  4
I worry about things:  4
I change my mood a lot:  4
I have a soft heart:  4
I am interested in people:  4
I insult people:  4
I am not really interested in others:  4
I am always prepared:  4
I leave my belongings around:  4
I follow a schedule:  4
I make a mess of things:  4
I have a rich vocabulary:  4
I have difficulty understanding abstract ideas:  4
I do not have a good imagination:  4
I use difficult words:  4


In [16]:
extraversion = 0
neuroticism = 0
agreeableness = 0
conscientiousness = 0
openness = 0
extraversion = (EXT1 + EXT2 + EXT3 + EXT4)/2.50
neuroticism = (EST1 + EST2 + EST3 + EST4)/2.50
agreeableness = (AGR1 + AGR2 + AGR3 + AGR4)/2.50
conscientiousness = (CSN1 + CSN2 + CSN3 + CSN4)/2.50
openness = (OPN1 + OPN2 + OPN3 + OPN4)/2.50
def roundfigure(a):
    x = int(a)
    y = x+1
    z = float((x+y)/2)
    print(x,y,z)
    import math
    if(a<z):
        n = math.floor(a)
    else:
        n = math.ceil(a)
    return n



In [19]:
ext = roundfigure(extraversion)
est = roundfigure(neuroticism)
agre = roundfigure(agreeableness)
csn = roundfigure(conscientiousness)
opn = roundfigure(openness)
print(extraversion,neuroticism,agreeableness,conscientiousness,openness)
print(ext,est,agre,csn,opn)



6 7 6.5
6 7 6.5
6 7 6.5
6 7 6.5
6 7 6.5
6.4 6.4 6.4 6.4 6.4
6 6 6 6 6


In [20]:
import numpy as np
xyze = np.array([gender1,age,opn,est,csn,agre,ext])
result = mul_lr.predict([xyze])
print(result)

['extraverted']


In [21]:
from sklearn import metrics

